name: Polling Miner

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-jan:
    name: Jan’s Miner
    runs-on: ubuntu-latest
    env:
      USER_ID: jan
      Auth_bearer: ${{ secrets.JAN_AUTH_BEARER }}
      API_URL:     ${{ secrets.API_URL }}
      REFERAL_URL: ${{ secrets.REFERAL_URL }}
      HOST_NAME:   ${{ secrets.HOST_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install requests

      - name: Run Jan’s mining step
        run: python mine.py

      - name: Commit state (on success)
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add state_jan.json
          git commit -m "Update next_run for jan" || echo "No change"
          git push

  run-marusa:
    name: Maruša’s Miner
    needs: run-jan
    runs-on: ubuntu-latest
    env:
      USER_ID: marusa
      Auth_bearer: ${{ secrets.MARUSA_AUTH_BEARER }}
      API_URL:     ${{ secrets.API_URL }}
      REFERAL_URL: ${{ secrets.REFERAL_URL }}
      HOST_NAME:   ${{ secrets.HOST_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install requests

      - name: Run Maruša’s mining step
        run: python mine.py

      - name: Commit state (on success)
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add state_marusa.json
          git commit -m "Update next_run for marusa" || echo "No change"
          git push
