name: Solar Heating Daemon

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - run: npm ci

      - name: Run continuous solar-control
        run: node solar-control.js
        env:
          SOLAREDGE_URL:    ${{ secrets.SOLAREDGE_URL }}
          SOLAREDGE_COOKIE: ${{ secrets.SOLAREDGE_COOKIE }}
          EWELINK_EMAIL:    ${{ secrets.EWELINK_EMAIL }}
          EWELINK_PASSWORD: ${{ secrets.EWELINK_PASSWORD }}
          EWELINK_REGION:   ${{ secrets.EWELINK_REGION }}
          EWELINK_APP_ID:   ${{ secrets.EWELINK_APP_ID }}
          EWELINK_APP_SECRET: ${{ secrets.EWELINK_APP_SECRET }}
